fix: Setting saturation params on logistic model when producing forec…
artefactory/streamlit_prophet pull request #12
Opened 2022-01-20 09:48 UTC by RameeA

## Description

Issue when setting saturation params and forecasting into the future. Root cause cap/floor columns not defined in future data frame.

![image](https://user-images.githubusercontent.com/37738513/150314478-89a54e2f-0382-40a1-8523-de0bc4b61cb8.png)

## Related Issue

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [x] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/artefactory/streamlit_prophet}/blob/main/CODE_OF_CONDUCT.md) document.
- [ x] I've read the [`CONTRIBUTING.md`](https://github.com/artefactory/streamlit_prophet}/blob/main/CONTRIBUTING.md) guide.
- [ x] I've updated the code style using `make format-code`.
- [ x] I've written tests for all new methods and classes that I created.
- [ x] I've written the docstring in Google format for all the methods and classes that I used.

2022-01-21 18:24 UTC, MaximeLutel requested changes
Hello @RameeA, thanks a lot for your pull request and for noticing this issue.
There are just minor changes to be made before I can merge it.
Thanks!

2022-01-21 18:24 UTC, MaximeLutel commented on streamlit_prophet/lib/dataprep/format.py
> +        future = add_cap_and_floor_cols(future, params)
Could we move this line out of the "else" statement, so that the ``add_cap_and_floor_cols`` function is called in any case?

2022-01-21 18:24 UTC, MaximeLutel commented on streamlit_prophet/lib/dataprep/format.py
> +        future = add_cap_and_floor_cols(future, params)
And also, would it be possible to add the text below in the parameter's part of the docstring of ``prepare_future_df`` and ``make_future_df`` functions?

params : Dict
      Dictionary containing all model parameters

Thanks a lot!

2022-01-22 03:53 UTC, RameeA commented
My pleasure @MaximeLutel - Awesome product you've developed here! I've committed the changes as requested.

2022-01-23 17:05 UTC, merged

2022-01-23 17:05 UTC, MaximeLutel commented
That's great thanks!